### ISSUE TITLE
Issue installing WP Plugin

### ISSUE THREAD

**Issue by jarute** [drfraker/listen-360-plugin#5]
I downloaded the zip file and tried to upload and install into my Word Press site but it will not install. I get the follow message. 

Installing Plugin from uploaded file: master.zip
Unpacking the package…

Installing the plugin…

The package could not be installed. No valid plugins were found.

Plugin install failed.

Return to Plugins page

Please let me know if you have a resolve to this issue.  thank you. 
You can contact me via my Facebook page http://www.facebook.com/alphakravct

**Comment by drfraker** [comment]
It won't work by installing master.zip. I think you will have to upload the file to your plugins directory. I made this a long time ago.
